import razorpay
import json

from django.shortcuts import redirect
from django.views import View
from django.views.generic import TemplateView

razorpay_client = razorpay.Client(auth=("<YOUR_KEY>", "<YOUR_SECRET>"))


class Charge(View):
    def post(self, request):
        amount = 5100

        # Payment ID generated by Razorpay
        payment_id = request.POST['razorpay_payment_id']

        # Payment forwarding by razorpay
        razorpay_client.payment.capture(payment_id, amount)

        # Payment data returned as a python dictionary by Razorpay
        payment_data = razorpay_client.payment.fetch(payment_id)

        # Redirect to custom success page, this "success" string is just defined
        # in payment_integrator/urls.py as name="success"
        return redirect("success")


class Pay(TemplateView):
    template_name = "payment.html"


class Success(TemplateView):
    template_name = "success.html"
